# This file manages the frontend and MongoDB in separate containers
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:80"
